version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - DATASOURCE_USERNAME=library
      - DATASOURCE_PASSWORD=123
      - WAIT_FOR=postgres:5432
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - nw
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=library
    networks:
      - nw
networks:
  nw: