DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
CREATE TABLE BOOK(ID UUID PRIMARY KEY, TITLE VARCHAR(255), AUTHOR UUID, GENRE UUID);
CREATE TABLE AUTHOR(ID UUID PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRE(ID UUID PRIMARY KEY, NAME VARCHAR(255));
